name: Terraform Deployment 
 
on: 
  push: 
    branches: [ "main" ] 
 
env:             
  AWS_REGION: us-east-1   
 
jobs: 
  CICD: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout 
      uses: actions/checkout@v4    #actions/checkout@v3 
    
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v4  #aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{ env.AWS_REGION }} 
 
    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v3   #hashicorp/setup-terraform@v2 
    
    - name: Terraform Init 
      run: terraform init 

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
 
    - name: Terraform Plan 
      run: terraform plan 
    
    - name: Terraform Apply 
      run: terraform apply --auto-approve